import 'package:flutter/material.dart';

void main(List<String> args) {
  debugPrint("ilçe : ${Constants.ilce}");
  debugPrint("Basım Tarihi : ${Constants.basimTarihi}");
  debugPrint("Bilgisayar Modeli : ${Constants.bilgisayarModeli}");
  debugPrint("boylam : ${Constants.boylam}");
  debugPrint("Çalıştığın Bölüm : ${Constants.calistiginBolum}");
  debugPrint("dergi adı : ${Constants.dergiAdi}");
  debugPrint("doğum tarihi : ${Constants.dogumTarihi}");
  debugPrint("dosya adı : ${Constants.dosyAdi}");
  debugPrint("enlem : ${Constants.enlem}");
  debugPrint("etkinlik günü : ${Constants.etkinlikGunu}");
  debugPrint("faks : ${Constants.faks}");
  debugPrint("fatura tarihi : ${Constants.faturaTarihi}");
  debugPrint("yüzde zam miktarı  : ${Constants.yuzdeZamMiktari.toString()}");
  debugPrint("ürün miktarı : ${Constants.urunMiktari.toString()}");
  debugPrint("ürün fiyatı : ${Constants.urunFiyati.toString()}");
  debugPrint("satılan miktar : ${Constants.satilanMiktar.toString()}");
  debugPrint("posta kodu : ${Constants.postaKodu.toString()}");
  debugPrint("ödeme miktarı : ${Constants.odemeMiktari.toString()}");
  debugPrint("mekan puanı : ${Constants.mekanPuani.toString()}");
  debugPrint("medeni hal : ${Constants.medeniHal.toString()}");
  debugPrint("kullanılan dakika : ${Constants.kullanilanDakika.toString()}");
  debugPrint("ekran boyutu : ${Constants.ekranboyutu.toString()}");
  debugPrint("eft Miktarı : ${Constants.eftMiktari.toString()}");
  debugPrint("Daire sayısı : ${Constants.daireSayisi.toString()}");
  debugPrint("borç : ${Constants.borc.toString()}");
  debugPrint("basıç : ${Constants.basinc.toString()}");
  debugPrint("yolculuk çıkış saati : ${Constants.yolculukCikisSaati}");
  debugPrint("yemek adi : ${Constants.yemekAdi}");
  debugPrint("video yorumu : ${Constants.videoYorumu}");
  debugPrint("video adı : ${Constants.videoAdi}");
  debugPrint("insta adresi : ${Constants.instaAdresi}");
  debugPrint("kargo takip no : ${Constants.kargoTakipNo}");
  debugPrint("kıta : ${Constants.kita}");
  debugPrint("kullanım süresi : ${Constants.kullanimSuresi}");
  debugPrint("kupon kodu : ${Constants.kuponKodu}");
  debugPrint("kupon süresi : ${Constants.kuponSuresi}");
  debugPrint("mahalle adı : ${Constants.mahAdi}");
  debugPrint("musteri soyadı : ${Constants.musteriSoyadi}");
  debugPrint("müzik süresi : ${Constants.muzikSuresi}");
  debugPrint("ödeme günü : ${Constants.odemeGunu}");
  debugPrint("ödeme saati : ${Constants.odemeSaati}");
  debugPrint("otobüs hatto : ${Constants.otobusHatti}");
  debugPrint("renk : ${Constants.renk}");
  debugPrint("renk kodu : ${Constants.renkKodu}");
  debugPrint("resim formatı : ${Constants.resimFormati}");
  debugPrint("şirket : ${Constants.sirket}");
  debugPrint("telefon modeli : ${Constants.telefonModeli}");
}

class Constants {
  static String ilce = "Beşiktaş";
  static String kita = "Avruğa";
  static String odemeSaati = "12:19";
  static String faks = "+902127659898";
  static String instaAdresi = "@cetnburak";
  static String musteriSoyadi = "çetin";
  static String calistiginBolum = "Mobile Development";
  static String dogumTarihi = "15/04/1997";
  static String videoYorumu =
      "Güzel işler yapmaya devam ediyorsun, böyle devam et. THUMBS UP";
  static String telefonModeli = "iPhone";
  static String dergiAdi = "Uykusuz";
  static String basimTarihi = "23/12/2020";
  static String enlem = "36-42";
  static String boylam = "26-45";
  static String yemekAdi = "Taze Fasulye";
  static String sirket = "KESiN";
  static String videoAdi = "GetX nedir? Nasıl kullanılır?";
  static String muzikSuresi = "3:01";
  static String dosyAdi = "bootcamp_lesson1.dart";
  static String resimFormati = ".png";
  static String renk = "mavi ";
  static String renkKodu = "#f2f2f2";
  static String bilgisayarModeli = "Apple";
  static String kullanimSuresi = "14:13";
  static String etkinlikGunu = "Tuesday";
  static String odemeGunu = "14.04.2024";
  static String yolculukCikisSaati = "14:10";
  static String mahAdi = "Hattat Tahsin Mah.";
  static String otobusHatti = "34f";
  static String kargoTakipNo = "234412klkofqd122";
  static String kuponSuresi = "23.03.2023 000:00:00";
  static String kuponKodu = "12344kksdı12";
  static String faturaTarihi = "23/12/2023";
  static bool medeniHal = false;
  static int borc = 34000;
  static int yuzdeZamMiktari = 25;
  static int daireSayisi = 50;
  static int postaKodu = 34000;
  static int kullanilanDakika = 10;
  static int basinc = 1;
  static int urunMiktari = 12;
  static int mekanPuani = 4;
  static int satilanMiktar = 400;
  static double urunFiyati = 109.99;
  static double eftMiktari = 1490.00;
  static double odemeMiktari = 1550.90;
  static double ekranboyutu = 15.3;
}
